node {
checkout scm
    env.DOCKER_API_VERSION="1.23"
    appName = "webapp/logicalis-web"
    registryHost = "10.20.97.100:8500/"
    imageName = "${registryHost}${appName}:${env.BUILD_ID}"
    env.BUILDIMG=imageName
    checkout scm

    def app

    stage('Clone repository') {
        checkout scm
        sh """
        #!/bin/bash
        zip -r /var/lib/jenkins/workspace/ICP-development/lab2-app.zip /var/lib/jenkins/workspace/ICP-development/*
        """
    }
    stage('Build image') {
        app = docker.build("lnd87/icp:webapp")
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
    }
    stage('Deploy new Docker Image') {
       sh """
       #!/bin/bash
       NAMESPACE=development
       set +e
       kubectl config set-cluster logicaliscluster.icp --server=https://10.20.97.96:8001 --insecure-skip-tls-verify=true
       kubectl config set-context logicaliscluster.icp-context --cluster=logicaliscluster.icp
       kubectl config set-credentials admin --token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZDJlYTRkODJmdTRncnhvcXY3ZWwiLCJyZWFsbU5hbWUiOiJjdXN0b21SZWFsbSIsInVuaXF1ZVNlY3VyaXR5TmFtZSI6ImFkbWluIiwiaXNzIjoiaHR0cHM6Ly9sb2dpY2FsaXNjbHVzdGVyLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiIyZWJhMDllNGIxZDM5MWZmOGZmYmYxMjBjMjZiYjA0YiIsImV4cCI6MTUyNjk3MTA0NSwiaWF0IjoxNTI2OTcxMDQ1LCJzdWIiOiJhZG1pbiIsInRlYW1Sb2xlTWFwcGluZ3MiOltdfQ.S7C9Ya_1HN4VGZjGa_TxEjq3CHIWOFZSJLkaKjef8QFc1zXUPAflmh8hHzD7NLaTHNkyxEp2rus6k6YlVBS5gtTYcEmkjRCxEbTw_cR0rMTcuu8eyNdM7aXcK3ypOkvBJF5sVwWtwvAoLnjOom6mVn9E2xfdzB61zqWHnflrAED-DzmxS9GqVNuTBtOE1lb_iqRC0WuZqlzD3B4Z2IhrsjtX2KsdzEVNPiOpIhA-lTt7ukSEhxm5gRQqnd7GAIqodDI8CkWgY64XtY9_0TMdas5pOvTdwBT3WFGTgfVdS7gCvc-X0QZqQ6yRnsI0agifSxXW7qnZkFflDelCoFjo1A
       kubectl config set-context logicaliscluster.icp-context --user=admin --namespace=default
       kubectl config use-context logicaliscluster.icp-context
       kubectl --namespace=development set image deployment/webapp-logicalis  webapp-logicalis=lnd87/icp:latest
       kubectl --namespace=development rollout status deployment/webapp-logicalis
       """
            }
}
}
