kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openshiftexdev.jenkinswebhook-buildconfig.jlbg
  namespace: jlbg
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/jlbg/buildconfigs/openshiftexdev.jenkinswebhook-buildconfig.jlbg
  uid: 04388e6e-d5a4-11e9-a805-0a580a82005b
  resourceVersion: '14509779'
  creationTimestamp: '2019-09-12T21:26:43Z'
  labels:
    name: openshiftexdev.jenkinswebhook-buildconfig.jlbg
spec:
  nodeSelector: {}
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any
          options {
            timeout(time: 2, unit: 'MINUTES') 
          }
          stages {
          stage('Location') {
            steps {
              sh 'oc project jlbg'
              sh 'echo "Using Project: `oc project`"'
              script {
                openshift.withCluster() {
                  openshift.withProject() {
                    echo "Using project: ${openshift.project()}"
                    }
                  }
                }
              }
            }
          stage('Starting Build...') {
            steps {
              sh 'oc project jlbg'
              sh 'echo "Using Project: `oc project`"'
              sh 'oc start-build buildconfig.build.openshift.io/openshiftexdev'
              }
            }
          }
        }
  postCommit: {}
  source:
    type: None
  triggers:
    - type: GitLab
      gitlab:
        secretReference:
          name: jenkinswebhook.secret
  runPolicy: Serial
status:
  lastVersion: 8
