kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openshiftexfromdevtopro
  namespace: jlbg
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/jlbg/buildconfigs/openshiftexfromdevtopro
  uid: 8f69f40e-d5ff-11e9-b78e-0a580a810064
  resourceVersion: '14518339'
  creationTimestamp: '2019-09-13T08:22:01Z'
  labels:
    app: openshiftexfromdevtopro
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'openshiftexfromdevtopro:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:7.2'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'http://10.20.97.80/webdemo-kubernetes/openshiftex.git'
  triggers:
    - type: GitHub
      github:
        secret: g4lSqHr4vyt2B6Pe4cca
    - type: Generic
      generic:
        secret: 5FQXRlmkvxZ3qs8a6qJy
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:6f697ac1aa68f20b76e197068508d43a27f15c773024173510e1be383a869554
  runPolicy: Serial
status:
  lastVersion: 1
